### ISSUE TITLE
Multiple translations for one word

### ISSUE THREAD

**Issue by logos88** [artetxem/mitzuli#13]
Hello. I have used Mitzuli a little and when I translate a word it only gives me one translation. What happens with the words with multiple definitions?

For instance, If I translate bold from English to Spanish it translates it like intrépido. But it means "negrita" too.

If the translation is not complete with all the possibilities is useless and can bring you to a mistake.

**Comment by artetxem** [comment]
Mitzuli is a machine translator, not a dictionary. If it were to give every possible translation for every single word in the input text the output would be completely unusable. The idea is that the system should choose the correct translation for each word in the given context.

In any case, the machine translation engine and the language pairs in Mitzuli are not developed directly by me (they are mostly based on Apertium), so your request is beyond the scope of this project.
