### ISSUE TITLE
How to improve dictionaries

### ISSUE THREAD

**Issue by logos88** [artetxem/mitzuli#14]
Where does mitzuli gets the dictionaries from? Is there any way to help to improve them?

For instance, quickdic app gets the dictionaries from wiktionary so if you find one word that is not translated you can go to that page and fix it.

I found for example that the translation of "filthy" from English to Spanish is not possible in Mitzuli. If it used wiktionary I could go to the web and fill the gap.

**Comment by artetxem** [comment]
Most of the language pairs in Mitzuli are based on Apertium. If you want to contribute to this project by adding more entries to their dictionaries, you should have a look at their wiki at http://wiki.apertium.org and contact them directly. In any case, please note that machine translation is not only about dictionaries (you have to take care of other things like morphology, syntax etc.), so things won't be as easy as you expect probably.
