### ISSUE TITLE
Request: English to English

### ISSUE THREAD

**Issue by Rbagman** [artetxem/mitzuli#22]
Request: English to English

**Comment by kranich** [comment]
:+1:

**Comment by artetxem** [comment]
Eh? Why would you want an option to translate from English to English (i.e. copy the input text into the output text)? Please develop your idea.

**Comment by kranich** [comment]
I would find it useful to be able to look up the definition of an English word in an English dictionary, i.e. a dictionary that describes the meanings of the word in English text.

**Comment by Rbagman** [comment]
I asked before I realized there are supposed to be copy/paste icons in the upper window. I have only been able to select text from the upper window a few times since I've installed the app.

I have reinstalled it and I have yet to be able to select and copy text from the upper window.

https://ibin.co/2gaunM9zxJjF.png
https://imagebin.ca/v/2gauZJ4WMC3T
https://imagebin.ca/v/2gauDlP3VDMt

Edit:

If I turn the device to landscape mode I can see the copy/paste icons; and turn back to portrait mode they remain. Getting them to appeat in portrait mode is the problem I am experiencing.

https://imagebin.ca/v/2gb0y8TiVQIu
https://imagebin.ca/v/2gb16Z8CfKyK

**Comment by artetxem** [comment]
@kranich That would of course be useful, but is out of the scope of this app. This is a machine translator app, not a dictionary (and even less a monolingual dictionary).

@Rbagman You posted your message to the wrong thread. And, from what I see, you are able to select text. I see no reason why text selection would work in landscape mode and not in portrait mode.
