### ISSUE TITLE
I can't open the aplicaton

### ISSUE THREAD

**Issue by logos88** [artetxem/mitzuli#5]
Hello. I have installed Mitzuli from F-droid in a Moto G LTE with Android 4.4.4 and when I try to open it it says "Se ha detenido la aplicación". I have tried to reboot the smartphone, but the issue still persist.

**Comment by artetxem** [comment]
It looks like some native libraries are missing in the APK at F-Droid. It wasn't me who published the app at that store, so I can't help you with this. If you know where I can upload the correct APK I will do it, but I really don’t get why they published my app without even letting me know and then point their users to my issue tracker...

**Comment by xavivars** [comment]
@artetxem, probably you already know it, but just in case: at F-Droid, they don't "upload" the application, they just configure the F-Droid build servers to build it directly from your github repository

https://gitlab.com/fdroid/fdroiddata/commit/9ac3eb27e08c9a6f0fd67d0632df4e268994bc04

And they do it as soon as someone finds the code of a free app somewhere in a public repo (github, sourceforge, etc).

And you won't be able to "upload" the apk, as one of the requirements it has is they build the apks in their own build servers.

**Comment by artetxem** [comment]
Thanks @xavivars. I honestly didn't know how F-Droid worked and assumed that it was something similar to Google Play but just for free software. I still think that it would be nice if they told developers when they publish their apps or, at least, test what their release, but everything makes more sense now that I know how they work.

Anyway, this basically means that we have a build issue. I have had similar problems myself (some native libraries missing in the apk), but rebuilding the project has fixed them for me so I have not paid too much attention to this. It looks like I will have to now. In the meantime, I guess that F-Droid people should retire the app from their repository or find a workaround for it.

There is another issue, also. The app uses some API keys that are not set in this repository for obvious reasons so, unless they set their own API keys, the app at F-Droid will not be fully functional.

**Comment by nxvtcehw** [comment]
FWIW, I've installed the F-Droid version and it works fine online and offline.

**Comment by xavivars** [comment]
@artetxem, yeah, having they updloading "your" apps (even if they are allowed because of the license) without telling you could be improved, IMHO. 

On top of that, they have some "mocking" implementations of some libraries, so for example if you ever plan to add some advertisement in your apps (like we do at Softcatalà, just to get funding to pay the servers were we run the translation service - we're a non-profit), the ads will just "disappear" in F-Droid...

**Comment by nxvtcehw** [comment]
@xavivars 
I think those mock libraries are only used if there is no free version of that dependency available. F-Droid does not ban advertising, but it must be implemented with a free and open source library.

**Comment by artetxem** [comment]
Well, so it looks like, after all, the F-Droid version does not always crash on launch. However, some native libraries are missing for sure, so the app must crash at some point. @nxvtcehw, have you tried using camera translation? The app will probably crash as soon as you take a picture.

So I now think that the problem reported by @logos88 is not specific to the F-Droid version and, seeing some error reports, I would say that it is actually related to TTS. Unfortunately, the F-Droid version cannot use my API key for crash reporting, so it is not easy to confirm that. @logos88, could you tell us what TTS engines you have installed on your phone, please? You can see them at Settings -> Language & input -> Text-to-speech output.

**Comment by logos88** [comment]
I don't have a "Text-to-speech" option. Only Idioma y entrada de texto, Teclado y métodos de entrada y Ratón/Panel táctil.

**Comment by logos88** [comment]
I have think that I have some google apps uninstalled, is maybe because of that?

**Comment by artetxem** [comment]
@logos88 The bug is already identified with the help of @nordfalk, I just need to take some time to fix it. I suspect that the problem arises when there is no TTS engine installed as it is your case, but that is not relevant for fixing the bug. Thanks for your help though ;)

**Comment by artetxem** [comment]
I have just released a new version of the app that should fix this (it is not a proper fix really, but it should work). BTW, Mitzuli has been temporarily retired from F-Droid until the build issues are fixed, so you can download the updated version from Google Play.

@logos88 could you confirm that it works, please?

**Comment by logos88** [comment]
@artetxem I have just installed and works perfectly. Thanks for this awsome app!! I hope it will be again in F-Droid in the future since is what I like to use normally ;)

**Comment by artetxem** [comment]
So it looks like the workaround works! Thanks everybody for your help!
