### ISSUE TITLE
English -> German

### ISSUE THREAD

**Issue by nxvtcehw** [artetxem/mitzuli#6]
If you're taking requests English-German and German-English would be useful.

**Comment by artetxem** [comment]
The machine translation engine and the language pairs at Mitzuli are not developed by me (practically all the translation directions are based on Apertium). Developing a language pair for a RBMT system like Apertium requires weeks/months of work and the knowledge of the languages involved, and I cannot provide either of them. Sorry, but I have to close this issue.

**Comment by nxvtcehw** [comment]
Ah, I see. Thank you for this information.

**Comment by Cloufish** [comment]
So It's been 8 years and no German Translator? 
That's sad :(
