### ISSUE TITLE
where is the offline part is coming from?

### ISSUE THREAD

**Issue by irregularisnotrandom** [artetxem/mitzuli#8]
Hi

I was excited to try this because it said it is offline, but that does not seem to be the case because it still tries to go online. Maybe you should make it clear or provide some offline databases?

thanks

**Comment by artetxem** [comment]
For the app to work offline you first need to download each language pair by clicking on its corresponding pin. Here you have an example on how to do it for French-Catalan:

![Screenshots](http://i59.tinypic.com/124zspg.jpg)
