### ISSUE TITLE
New language feature request Finnish <->English 

### ISSUE THREAD

**Issue by krz37** [artetxem/mitzuli#9]
Hi, your application is really a good job. I just really miss the language that I am studying right now which is Finnish. Would it be possible to add it please? I truly want to say bye bye to Google Translate :)

**Comment by artetxem** [comment]
The machine translation engine and the language pairs in Mitzuli are not developed by me (they are mostly based on Apertium). Developing a language pair for a RBMT system like Apertium requires months of work and the knowledge of the languages involved, and I cannot provide either of them in this case. However, there is an ongoing work in Apertium to develop the Finnish-English language pair, and I would certainly add it to Mitzuli if a proper version were released.
